# Generated by Django 6.0 on 2025-12-06 07:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('balance__gte', Decimal('0.00'))), name='amount_gte_0.00')],
            },
        ),
        migrations.CreateModel(
            name='SystemWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('commission_tx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.transaction')),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='out_transactions', to='app.wallet')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inc_transactions', to='app.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['from_wallet', '-created_at'], name='app_transac_from_wa_a83b7f_idx'), models.Index(fields=['to_wallet', '-created_at'], name='app_transac_to_wall_8fa244_idx'), models.Index(fields=['created_at'], name='app_transac_created_675e08_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.01'))), name='amount_gte_0.01')],
                'unique_together': {('from_wallet', 'to_wallet')},
            },
        ),
    ]
